apiVersion: v1
kind: Service
metadata:
  name: cephalon-template-app
  labels:
    app.kubernetes.io/name: cephalon-template-app
    app.kubernetes.io/part-of: cephalon
    app.kubernetes.io/component: host
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cephalon-template-app
    app.kubernetes.io/component: host
  ports:
  - name: http
    port: 80
    targetPort: http
