using Cephalon.Engine.Configuration;
using Microsoft.Extensions.Configuration;

namespace Cephalon.Observability.GrafanaCloud.Configuration;

/// <summary>
/// Configures Grafana Cloud observability defaults on top of the shared Cephalon telemetry contract.
/// </summary>
public sealed class GrafanaCloudTelemetryExportOptions
{
    /// <summary>
    /// Initializes a new instance of the <see cref="GrafanaCloudTelemetryExportOptions" /> class.
    /// </summary>
    public GrafanaCloudTelemetryExportOptions()
    {
    }

    /// <summary>
    /// Gets or sets a value indicating whether the package should target the Grafana Cloud OTLP endpoint
    /// when no shared collector endpoint is configured.
    /// </summary>
    /// <remarks>
    /// This direct path is intended for the connection details Grafana Cloud generates through
    /// <c>OTEL_EXPORTER_OTLP_ENDPOINT</c> and <c>OTEL_EXPORTER_OTLP_HEADERS</c>. Teams that prefer a
    /// collector or gateway can keep using the shared <c>Endpoint</c> or <c>UseSelfHostedDefaults</c>
    /// contract instead.
    /// </remarks>
    public bool UseDirectGrafanaCloudEndpoint { get; set; }

    /// <summary>
    /// Gets or sets the base Grafana Cloud OTLP endpoint used for direct ingestion.
    /// </summary>
    /// <remarks>
    /// Set this to the Grafana Cloud OTLP endpoint generated by the stack administration console.
    /// For OTLP/HTTP the package treats this as the base endpoint and appends the signal-specific
    /// <c>/v1/traces</c>, <c>/v1/metrics</c>, or <c>/v1/logs</c> suffix automatically.
    /// </remarks>
    public string? Endpoint { get; set; }

    /// <summary>
    /// Gets or sets the raw OTLP headers string used for direct Grafana Cloud ingestion.
    /// </summary>
    /// <remarks>
    /// Use the standard OTLP <c>key=value</c> comma-separated format. This value usually comes
    /// directly from the generated <c>OTEL_EXPORTER_OTLP_HEADERS</c> environment variable.
    /// </remarks>
    public string? Headers { get; set; }

    /// <summary>
    /// Gets or sets the Grafana Cloud instance identifier used as the Basic-auth username when the
    /// package should build the Authorization header from structured settings.
    /// </summary>
    /// <remarks>
    /// This value is unrelated to the OpenTelemetry <c>service.instance.id</c> resource attribute.
    /// Use it together with <see cref="AccessPolicyToken" /> when you prefer configuration values over
    /// a prebuilt <see cref="Headers" /> string.
    /// </remarks>
    public string? InstanceId { get; set; }

    /// <summary>
    /// Gets or sets the Grafana Cloud access-policy token used as the Basic-auth password when the
    /// package should build the Authorization header from structured settings.
    /// </summary>
    public string? AccessPolicyToken { get; set; }

    /// <summary>
    /// Gets or sets the optional <c>service.namespace</c> resource attribute to stamp onto exported telemetry.
    /// </summary>
    public string? ServiceNamespace { get; set; }

    /// <summary>
    /// Binds Grafana Cloud telemetry export options from configuration.
    /// </summary>
    /// <param name="configuration">The application configuration root.</param>
    /// <param name="sectionPath">
    /// The configuration section path that contains the engine settings. The default is <c>Engine</c>.
    /// </param>
    /// <returns>The bound Grafana Cloud telemetry export options.</returns>
    public static GrafanaCloudTelemetryExportOptions FromConfiguration(
        IConfiguration configuration,
        string sectionPath = EngineSettings.SectionName)
    {
        ArgumentNullException.ThrowIfNull(configuration);

        var section = configuration
            .GetSection(sectionPath)
            .GetSection("Observability")
            .GetSection("Telemetry")
            .GetSection("GrafanaCloud");

        return FromSection(section);
    }

    internal static GrafanaCloudTelemetryExportOptions FromSection(IConfigurationSection section)
    {
        ArgumentNullException.ThrowIfNull(section);

        return new GrafanaCloudTelemetryExportOptions
        {
            UseDirectGrafanaCloudEndpoint = GetBoolean(section["UseDirectGrafanaCloudEndpoint"], defaultValue: false),
            Endpoint = Normalize(section["Endpoint"]),
            Headers = Normalize(section["Headers"]),
            InstanceId = Normalize(section["InstanceId"]),
            AccessPolicyToken = Normalize(section["AccessPolicyToken"]),
            ServiceNamespace = Normalize(section["ServiceNamespace"])
        };
    }

    private static string? Normalize(string? value)
    {
        return string.IsNullOrWhiteSpace(value) ? null : value.Trim();
    }

    private static bool GetBoolean(string? value, bool defaultValue)
    {
        return bool.TryParse(value, out var parsed) ? parsed : defaultValue;
    }
}
