<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CA1707</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Cephalon.Data.Debezium\Cephalon.Data.Debezium.csproj" />
    <ProjectReference Include="..\..\src\Cephalon.Data.MySql\Cephalon.Data.MySql.csproj" />
    <ProjectReference Include="..\..\src\Cephalon.Data.Oracle\Cephalon.Data.Oracle.csproj" />
    <ProjectReference Include="..\..\src\Cephalon.Data.Postgres\Cephalon.Data.Postgres.csproj" />
    <ProjectReference Include="..\..\src\Cephalon.MultiTenancy.Governance.AspNetCore\Cephalon.MultiTenancy.Governance.AspNetCore.csproj" />
    <ProjectReference Include="..\..\src\Cephalon.MultiTenancy.Governance\Cephalon.MultiTenancy.Governance.csproj" />
    <ProjectReference Include="..\..\tests\Cephalon.Tests.Support\Cephalon.Tests.Support.csproj" />
  </ItemGroup>
</Project>
